[package]
name = "book_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.20.2"

tokio = { version = "1.42.0", features = ["rt-multi-thread", "macros"] }
tokio-util = { version = "0.7.13", features = ["compat"] }
tokio-stream = "0.1.17"
futures = "0.3.31"

axum = "0.8.1"
axum-prometheus = "0.8.0"

tower = "0.5.2"
tower-http = { version = "0.6.2", features = ["trace"] }

tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"]}
sentry-tracing = "0.35.0"

reqwest = { version = "0.12.12", features = ["json", "stream"] }

serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"

teloxide = { version = "0.13.0", features = ["macros", "webhooks-axum", "cache-me", "throttle"] }

url = "2.5.4"

ctrlc = { version = "3.4.5", features = ["termination"] }

strum = "0.26.3"
strum_macros = "0.26.4"

base64 = "0.22.1"
textwrap = "0.16.1"
regex = "1.11.1"
chrono = "0.4.39"
dateparser = "0.2.1"

smallvec = { version = "1.13.2", features = ["serde"] }
smartstring = { version = "1.0.1", features = ["serde"] }

moka = { version = "0.12.9", features = ["future"] }

sentry = { version = "0.35.0", features = ["debug-images"] }
