[package]
name = "book_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.28.2", features = ["rt-multi-thread", "macros"] }
reqwest = { version = "0.11.18", features = ["json"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
log = "0.4.18"
pretty_env_logger = "0.5.0"
teloxide = { version = "0.12.2", features = ["macros", "webhooks-axum", "cache-me", "throttle"] }
url = "2.3.1"
ctrlc = { version = "3.4.0", features = ["termination"] }
strum = "0.24.1"
strum_macros = "0.24.3"
futures = "0.3.28"
base64 = "0.21.2"
tokio-util = { version = "0.7.8", features = ["compat"] }
textwrap = "0.16.0"
regex = "1.8.3"
chrono = "0.4.25"
dateparser = "0.2.0"
sentry = "0.31.3"
lazy_static = "1.4.0"
moka = { version = "0.11.1", features = ["future"] }
