[package]
name = "book_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.19.0"

tokio = { version = "1.37.0", features = ["rt-multi-thread", "macros"] }
tokio-util = { version = "0.7.10", features = ["compat"] }
tokio-stream = "0.1.15"
futures = "0.3.30"

axum = "0.7.5"
axum-prometheus = "0.6.1"

tower = "0.4.13"
tower-http = { version = "0.5.2", features = ["trace"] }

tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"]}
sentry-tracing = "0.32.3"

reqwest = { version = "0.12.4", features = ["json", "stream"] }

serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"

teloxide = { version = "0.12.2", features = ["macros", "webhooks-axum", "cache-me", "throttle"] }

url = "2.5.0"

ctrlc = { version = "3.4.4", features = ["termination"] }

strum = "0.26.2"
strum_macros = "0.26.2"

base64 = "0.22.0"
textwrap = "0.16.1"
regex = "1.10.4"
chrono = "0.4.38"
dateparser = "0.2.1"

smallvec = { version = "1.13.2", features = ["serde"] }
smartstring = { version = "1.0.1", features = ["serde"] }

moka = { version = "0.12.7", features = ["future"] }

sentry = { version = "0.32.3", features = ["debug-images"] }
